apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-sc"
  resources:
    requests:
      storage: 35Gi
---

piVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    app: web
spec:
  containers:
  - name: nginx
    image: nginx  
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic

---
apiVersion: v1 
kind: Service 
metadata: 
  name: ebs-dynamic    
spec: 
  type: LoadBalancer
  selector: 
    app: web 
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 80
    nodePort: 32000


