apiVersion: v1 
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx

---

apiVersion: v1 
Kind: Pod
metadata:
  name: pod-1
  namespace: expense
spec:
  containers:
  - name: cont-1
    image: nginx