apiVersion: v1 
kind: Pod
metadata:
  name: annotation
  annotations:
    buildURL: "https://jenkins.com"
    imageregistry: "https://hub.docker.com"
spec:
  containers:
  - name: cont-1
    image: nginx