apiVersion: v1 
kind: Pod
metadata:
  name: backend-ci
  labels:
    project: expense
    env: dev
    demo: ci 
spec:
  containers:
  - name: cont-1
    image: nginx

---

apiVersion: v1 
kind: Service
metadata: 
  name: nginx-ci
spec:
  selector: 
    project: expense
    env: dev
    demo: ci 
  ports:
  - port: 80
    targetPort: 80
