apiVersion: v1 
kind: Pod 
metadata:
  name: backend-np
  labels:
    project: expense
    demo: np
spec:   
  containers: 
  - name: nginx-np
    image: nginx 

---

apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-np 
spec:
  type: NodePort 
  selector:
    project: expense 
    demo: np
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007