apiVersion: v1 
kind: Pod 
metadata: 
  name: backend-lb
  labels:
    project: expense 
    demo: lb
spec: 
  containers: 
  - name: nginx-lb 
    image: nginx 

---

apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-lb
spec: 
  type: LoadBalancer 
  selector: 
    project: expense
    demo: lb 
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 32000