apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: backend
    demo: rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
      demo: rs
  template:
    metadata:
      labels:
        app: backend
        demo: rs 
    spec:
      containers:
      - name: nginx
        image: nginx

---

apiVersion: v1
kind: Service 
metadata: 
  name: frontend
spec:
  type: NodePort 
  selector: 
    app: backend 
    demo: rs 
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 80
    nodePort: 30007


