apiVersion: v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: backend
    demo: rs
spec:
  replicas: 5
  selector:
    matchLables:
      app: backend
      demo: rs
    template:
      metadata:
        labels:
          app: backend
          demo: rs 
      spec:
        containers:
        - name: nginx
          image: nginx


