apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeplyoment
  labels:
    project: expense
    demo: deplyoment 
spec:
  replicas: 3
  selector: 
    matchLabels:
      project: expense 
      demo: deplyoment 
  template:
    metadata:
      labels:
        project: expense 
        demo: deplyoment 
    spec: 
      containers: 
      - name: nginx 
        image: nginx 
        ports:
        - containerPort: 80
--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: frontend
spec: 
  type: LoadBalancer
  selector: 
    project: expense 
    demo: deplyoment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    
