apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-ds
  namespace: expense  # Optional: remove if you want to use the default namespace
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
